version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # default user is "opam"
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules:cached
      - opam:/home/opam/.opam:cached
      - build:/workspace/_build:cached
      - ${HOME}${USERPROFILE}/.ssh:/home/opam/.ssh
      - ${HOME}${USERPROFILE}/.gitconfig:/home/opam/.gitconfig
      - ${HOME}${USERPROFILE}/.gitignore_global:/home/opam/.gitignore_global
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../../framework/frontend/dist:/workspace/framework
    environment:
      - DATABASE_URL=mariadb://root@database-root:3306/development
      - DATABASE_URL_TENANT_TEST=mariadb://root@database-tenant:3306/test_econ
      - DATABASE_SKIP_DEFAULT_POOL_CREATION=true
      - DATABASE_CHOOSE_POOL=root
      - OPAMSOLVERTIMEOUT=180
      - PUBLIC_URL=http://localhost:3016
      - SMTP_HOST=smtp.uzh.ch
      - SMTP_PASSWORD=${ECON_SMTP_APP_PASSWORD}
      - SMTP_PORT=587
      - SMTP_SENDER=test@econ.uzh.ch
      - SMTP_START_TLS=true
      - SMTP_USERNAME=ecserv
      - VERSION=dev
      - ECON_PACKAGE_REGISTRY_READ_TOKEN
    depends_on:
      - database-root
      - database-tenant
    ports:
      - 3016:3000
      - 3017:3000
    command: sleep infinity

  database-root:
    image: mariadb:10.6
    command: --max_allowed_packet=629145600
    ports: [3316:3306]
    environment:
      - TZ=Europe/Zurich
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=development
      - MYSQL_USER=root
    volumes:
      - ./data/db-root:/var/lib/mysql
      - ./init_root:/docker-entrypoint-initdb.d/:ro

  database-tenant:
    image: mariadb:10.6
    command: --max_allowed_packet=629145600
    ports: [3317:3306]
    environment:
      - TZ=Europe/Zurich
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=dev_econ
      - MYSQL_USER=root
    volumes:
      - ./data/db-tenant:/var/lib/mysql
      - ./init_tenant:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer:standalone
    restart: always
    ports: [8080:8080]
    depends_on:
      - database-root
      - database-tenant

volumes:
  opam:
  node_modules:
  build:
