name: CI
on:
  push:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      EMAIL_RATE_LIMIT: 3600
      MATCHER_MAX_CAPACITY: 80
      MYSQL_DATABASE: test_econ
      MYSQL_ROOT_PASSWORD: password
      DB_ROOT_PORT: 3306
      DB_TENANT_PORT: 3307
    services:
      database-root:
        image: mariadb:10.6
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        options: --port ${{ env.DB_ROOT_PORT }} --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      database-tenant:
        image: mariadb:10.6
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        options: --port ${{ env.DB_TENANT_PORT }} --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test with Docker
        uses: addnab/docker-run-action@v3
        env:
          DATABASE_URL: mariadb://root:${{ env.MYSQL_ROOT_PASSWORD }}@database-root:${{ env.DB_ROOT_PORT }}/${{ env.MYSQL_DATABASE }}
          DATABASE_URL_TENANT_TEST: mariadb://root:${{ env.MYSQL_ROOT_PASSWORD }}@database-tenant:${{ env.DB_TENANT_PORT }}/${{ env.MYSQL_DATABASE }}
          SIHL_ENV: test
          SMTP_SENDER: test@econ.uzh.ch
          TEST_EMAIL: test@econ.uzh.ch
        with:
          image: ocaml/opam:debian-10-ocaml-4.12
          options: -v ${{ github.workspace }}:/app -w /app -e DATABASE_URL -e DATABASE_URL_TENANT_TEST -e TEST_EMAIL -e SMTP_SENDER -e SIHL_ENV
          run: |
            ping -c 4 database-root
            ping -c 4 database-tenant

            echo $DATABASE_URL_TENANT_TEST
            echo "${{ env.MYSQL_ROOT_PASSWORD }}"

            sudo apt-get -y update && sudo apt-get install -y netcat
            echo "======= checking port open"
            nc database-root ${{ env.DB_ROOT_PORT }}
            nc database-tenant ${{ env.DB_TENANT_PORT }}
            nc database-root 3306
            nc database-tenant 3307

            sudo apt-get install -y mariadb-client
            echo "======= try to connect mysql"
            mysql -u root -p=${{ env.MYSQL_ROOT_PASSWORD }} -h database-root -P ${{ env.DB_ROOT_PORT }} -e "show databases;"
            mysql -u root -p=${{ env.MYSQL_ROOT_PASSWORD }} -h database-tenant -P ${{ env.DB_TENANT_PORT }} -e "show databases;"
            mysql -u root -p=password -h database-root -P 3306 -e "show databases;"
            mysql -u root -p=password -h database-tenant -P 3307 -e "show databases;"


            # Reclaim required directory permissions
            sudo chown -R opam .

            # Build and test executable
            /app/scripts/build.sh

            # Restore directory permissions to avoid conflicts
            sudo chown -R 1001:123 .

      - uses: actions/upload-artifact@v3
        with:
          name: run.exe
          path: _build/default/pool/run/run.exe

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: tests
          path: _build/default/pool/test/

      - name: Notify about failure
        if: failure()
        run: |
          # Restore directory permissions to avoid conflicts
          ls -la .
          whoami
          chown -R 1001:123 .

          pwd
          cat << EOF > message.json
          {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Pipeline failed!","themeColor":"ff0000","title":"$GITHUB_REPOSITORY pipeline failed 💢!","sections":[{"facts":[{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"},{"name":"Commit:","value":"$GITHUB_SHA"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
          EOF
          
          ls -la .
          curl -X POST ${{ secrets.ECON_TEAMS_WEBHOOK }} --header 'Content-Type: application/json' -d @message.json

